GENOME: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.fasta"
GTF: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Homo_sapiens/NCBI/GRCh38/Annotation/Genes/genes.gtf"
#GENOME: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa"
#GTF: "/rds/project/yhbl2/rds-yhbl2-genehunter/SM/annotations/Homo_sapiens/UCSC/hg38/Annotation/Genes/genes.gtf"
DBSNP: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.dbsnp138.vcf"
INDELS: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.known_indels.vcf"
GOLD_STANDARD: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Mills_and_1000G_gold_standard.indels.hg38.vcf"
INDEX: "/rds/project/rds-O11U8YqSuCk/SM/annotations/StarGRCh38Index"
ADAPTERS: "CTGTAGGCACCATCAAT"
RG: ""
INTERVALS: "intervals.list" 
PON_DB: "pon_db" #PON_DB path 
THREADS: 4
AFONLYGNOMAD: af-only-gnomad.hg38.vcf.gz
NORMALS_PANEL: "pon.vcf.gz"
MEMORY: "-Xmx40g" 
