SAMPLES: ['n1', 't1']
GENOME: "/home/ec2-user/GATK_Resources/Homo_sapiens_assembly38.fasta"
DBSNP: "/home/ec2-user/GATK_Resources/Homo_sapiens_assembly38.dbsnp138.vcf"
INDELS: "/home/ec2-user/GATK_Resources/Homo_sapiens_assembly38.known_indels.vcf"
GOLD_STANDARD: "/home/ec2-user/GATK_Resources/Mills_and_1000G_gold_standard.indels.hg38.vcf"
EXCL_HG38: "human.hg38.excl.tsv"
GTF: "/rds/project/rds-O11U8YqSuCk/SM/annotations/Mus_musculus/Ensembl/GRCm38/Annotation/Genes/genes.gtf"
CHROMOSOMES: ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11','chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20' , 'chr21', 'chr22', 'chrX', 'chrY', 'chrM'] 

RG: "A00489_467.HT3G5DMXX.s_2"
ALL_VCF: "WES_tier4.vcf"
INTERVALS: "intervals.list" 
PON_DB: "pon_db" #PON_DB path 
THREADS: 3
AFONLYGNOMAD: af-only-gnomad.hg38.vcf.gz
NORMALS_PANEL: "pon.vcf.gz" 
