GENOME: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.fasta"

DBSNP: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.dbsnp138.vcf"
INDELS: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Homo_sapiens_assembly38.known_indels.vcf"
GOLD_STANDARD: "/rds/project/rds-O11U8YqSuCk/SM/annotations/gatkresources/Mills_and_1000G_gold_standard.indels.hg38.vcf"

RG: ""
INTERVALS: "intervals.list" 
PON_DB: "pon_db" #PON_DB path 
THREADS: 3
AFONLYGNOMAD: af-only-gnomad.hg38.vcf.gz
NORMALS_PANEL: "pon.vcf.gz"
MEMORY: "-Xmx40g" 
